### ISSUE TITLE
Reset the starting point

### ISSUE THREAD

**Issue by suntong** [micmro/performance-bookmarklet#46]
When would performance-bookmarklet start its data collection?
Would it always start from the very beginning?
Is it possible to let performance-bookmarklet to, "_forget the past, start data collection from now_"? 

Thanks

**Comment by micmro** [comment]
Sorry for the very late reply 😓.

performance-bookmarklet gets it's data from the _Resource_ & _Navigation Timing APIs_ that the browser provides.
If `performance.setResourceTimingBufferSize` had not been called with another number ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API#Managing_the_resource_buffer) has a pretty nice explanation) the default is to store the last 150 resource timing entries (requests) since the beginning of the current pages request cycle (`navigationStart` event of the Navigation Timing API).

Technically it would be possible, but it might be better to just use the browser tools for this.

**Comment by suntong** [comment]
thanks @micmro.
